name: Build x86 and arm Image

on:
  pull_request:
    branches:
      - exc-*
  push:
    branches:
      - ecx-*
env:
  VERSION: v3.5.1.2

jobs:
  docker-image:
    name: Build x86 and arm Image
    runs-on: ubuntu-18.04
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.7
      id: go
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: v0.9.1
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build Docker image
      run: |
        make build-multi-cephcsi
